### ISSUE TITLE
Create a generic list() function for css list properties

### ISSUE THREAD

**Issue by notoriousb1t** [typestyle/csx#13]
Example
```ts
cssRule('body', {
  backgroundImage: list(
    linearGradient(/* */), 
    linearGradient(/* */)
  )
})
```

**Comment by notoriousb1t** [comment]
@basarat  I'm on the fence about this.  Options:

- We could create a second type for lists in typestyle: CSSList<T extends string> because only select functions take a list and we would have to lie to the compiler about the value in "type"
- We could handle this at a property level

```ts
style({
  backgroundImage: csx.backgroundImage().and().and()
})
```

**Comment by basarat** [comment]
even if you do it at a `property level` you would still need to add support at the type level. I might be wrong here :rose:

**Comment by notoriousb1t** [comment]
That is true, to create property specific helpers we would have to be even more specific.  Hmm...

**Comment by notoriousb1t** [comment]
Added a naive implementation in ef8b46d3220bd0d0d4794c22797ea93f5008b4c3
