### ISSUE TITLE
`quote` function

### ISSUE THREAD

**Issue by basarat** [typestyle/csx#16]
Revisiting https://github.com/typestyle/typestyle/issues/33 

It makes sense in `csx`. Usage `content: csx.quote('hello world')`

precedence http://sass-lang.com/documentation/Sass/Script/Functions.html#quote-instance_method.

:rose:

**Comment by notoriousb1t** [comment]
Right with you on this one.  I don't know that it is entirely necessary, but it has precedence

**Comment by notoriousb1t** [comment]
Added in https://github.com/typestyle/csx/commit/d9d73e0652babaa9b70f6249173f37a9456ae336
