### ISSUE TITLE
`important` function

### ISSUE THREAD

**Issue by basarat** [typestyle/csx#17]
If people want to add important to a property: 

```
color: csx.important(csx.red)
```
Similar to https://github.com/typestyle/csx/issues/16 :rose:

**Comment by notoriousb1t** [comment]
😬 I don't like it, but it should definitely be in the library.  

I don't think it has any opportunity to be extended, but I am looking for a way to convert helpers toString at the last possible moment. Running into a bit of an issue with returning a generic object with the same "type".  I might have to lie to the compiler a little bit to make them work properly.

**Comment by notoriousb1t** [comment]
Added in https://github.com/typestyle/csx/commit/dc8bf4d884bf6af76ea5074e22a28c4c0eae2a4f
