### ISSUE TITLE
Create unit helpers px(), em(), rem(), percent(), viewHeight(), viewWidth()

### ISSUE THREAD

**Issue by notoriousb1t** [typestyle/csx#20]
**Acceptance criteria:**

- Should go in src/units.ts
- Should have at least one test in src/tests/units.ts
- Should export in src/index.ts
- Signatures should be: 

```px(val: number): CSSLength```
```em(val: number): CSSLength```
```rem(val: number): CSSLength```
```viewHeight(val: number): CSSLength```
```viewWidth(val: number): CSSLength```
```percent(val: number): CSSPercentage```

**Comment by notoriousb1t** [comment]
Added in https://github.com/typestyle/csx/commit/a0ac5b433a28bbd6f9362baf779ce9e82ed5c04f

**Comment by basarat** [comment]
Sweet 🍬 :rose:
