### ISSUE TITLE
quote() doesn't escape ' or "

### ISSUE THREAD

**Issue by notoriousb1t** [typestyle/csx#21]
Notes from @basarat  in https://github.com/typestyle/csx/commit/cfd1fc39db457547e01282d21f1462e5c66b2481

**Comment by notoriousb1t** [comment]
I'm trying to figure out why we need to double escape the ' in the string.

**Comment by basarat** [comment]
There is no double escaping, only single escaping. 

The JS strings are equivalent : `"ta ' da" == 'ta \' da'`, i.e there is just a quote, no `\'` (slash + quote) in that string. 

The string we want to output is `'ta \' da'`. In js that can be written as `"'ta \\' da'"`. 

![image](https://cloud.githubusercontent.com/assets/874898/21199985/c849985c-c299-11e6-9872-2161800de866.png)

If someone gives us the string `'hello'` e.g. `"'hello'"` in js 

![image](https://cloud.githubusercontent.com/assets/874898/21200033/f903cada-c299-11e6-9405-674f61ae1909.png)

We want to write `'\'hello\''` in CSS. Hence that transform.  Hope that helps :rose:

**Comment by notoriousb1t** [comment]
The 'ta \' da' example helped me understand what you were talking about.  You are talking about quotes inside the quoted string. 👍

**Comment by notoriousb1t** [comment]
Fixed in ef8b46d3220bd0d0d4794c22797ea93f5008b4c3
