### ISSUE TITLE
Add `border` shorthand helper function

### ISSUE THREAD

**Issue by markvandenbrink** [typestyle/csx#25]
https://developer.mozilla.org/en-US/docs/Web/CSS/border
https://developer.mozilla.org/en-US/docs/Web/CSS/border-left
https://developer.mozilla.org/en-US/docs/Web/CSS/border-right
https://developer.mozilla.org/en-US/docs/Web/CSS/border-top
https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom

**Comment by notoriousb1t** [comment]
It looks like we implemented this in https://github.com/typestyle/csx/blob/master/src/border.ts at some point but didn't close this issue.  There is a border shorthand for color, style, property and a helper for borderWidth that can set left, right, top, and bottom.  One of those should work for each of those properties
