### ISSUE TITLE
Create minified version for CDNs

### ISSUE THREAD

**Issue by notoriousb1t** [typestyle/csx#29]
I'm thinking webpack + ts-loader + uglify to a /dist folder

**Comment by basarat** [comment]
In case you haven't seen it : https://unpkg.com/#/. You don't need to add to the git (of course). Also I would recommend folder `umd` for clarity of purpose :rose:

**Comment by notoriousb1t** [comment]
I haven't used unpkg.com before, but I will now 😄 .  This was committed in https://github.com/typestyle/csx/commit/2783736e32d5e0ceefc320613d054b5632d06ad3 and published to npm in 8.2.1 and available at 

https://unpkg.com/csx@8.2.1/umd/csx.js
https://unpkg.com/csx@8.2.1/umd/csx.min.js
