### ISSUE TITLE
background shorthand doesn't handle size correctly

### ISSUE THREAD

**Issue by kellycampbell** [typestyle/csx#80]
From https://developer.mozilla.org/en-US/docs/Web/CSS/background:

> The <bg-size> value may only be included immediately after <position>, separated with the '/' character, like this: "center/80%".

This library outputs it with spaces and doesn't require both position and size to be specified. 

Example case that doesn't work:

```
<div className={style(
  {background: csx.background({
    repeat: 'no-repeat', size: 'cover', image: `url(${backgroundImg})`})} 
)}>
```

Adding position: 'center' doesn't fix the above. I have to do a separate `backgroundSize: 'cover'` attribute.

**Comment by notoriousb1t** [comment]
I put in a fix for background size and added a type restriction to prevent size without having a position specified in https://github.com/typestyle/csx/commit/447b2447bb66d3238ab21cfa5e3345cb233ae816. I will post again once I have a version out.

**Comment by notoriousb1t** [comment]
[9.0.2](https://github.com/typestyle/csx/releases/tag/v9.0.2) is out with fixes Thank you for letting us know 😄
